### ISSUE TITLE
install problem in windows (python in anaconda)

### ISSUE THREAD

**Issue by zerodrying** [cudamat/cudamat#100]
I have a problem to install the cudamat in anacoda. I use pip install , and get the follow error. I downloade the microsoft visual studio 2019

(base) C:\Users\Verfahrenstechnik\Desktop\cudamat-master>pip install --user -e.
Obtaining file:///C:/Users/Verfahrenstechnik/Desktop/cudamat-master
Installing collected packages: cudamat
  Running setup.py develop for cudamat
    Complete output from command C:\Users\Verfahrenstechnik\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Verfahrenstechnik\\Desktop\\cudamat-master\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    running develop
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing top-level names to cudamat.egg-info\top_level.txt
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    running build_ext
    building 'cudamat.libcudamat' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Verfahrenstechnik\Desktop\cudamat-master\setup.py", line 121, in <module>
        cmdclass={'build_ext': CUDA_build_ext})
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Verfahrenstechnik\Desktop\cudamat-master\setup.py", line 41, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\distutils\_msvccompiler.py", line 423, in compile
        self.spawn(args)
      File "C:\Users\Verfahrenstechnik\Desktop\cudamat-master\setup.py", line 70, in spawn
        os.path.dirname(find_executable("cl.exe", PATH))
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\ntpath.py", line 243, in dirname
        return split(p)[0]
      File "C:\Users\Verfahrenstechnik\Anaconda3\lib\ntpath.py", line 205, in split
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

    ----------------------------------------
Command "C:\Users\Verfahrenstechnik\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Verfahrenstechnik\\Desktop\\cudamat-master\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in C:\Users\Verfahrenstechnik\Desktop\cudamat-master\

Then I also use the pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip.
It shows follow error.

C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-q_p29uw_\setup.py:23: UserWarning: MSVC (cl.exe) not found on PATH. Compilation may fail. Either set PATH to include the path to MSVC, or set NVCCFLAGS=--compiler-bindir=... to define it. Possibly also set NVCCFLAGS=--cl-version=2010 to override nvcc's MSVC version detection.
    warnings.warn("MSVC (cl.exe) not found on PATH. Compilation may "
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
  running egg_info
  creating cudamat.egg-info
  writing cudamat.egg-info\PKG-INFO
  writing dependency_links to cudamat.egg-info\dependency_links.txt
  writing top-level names to cudamat.egg-info\top_level.txt
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  reading manifest file 'cudamat.egg-info\SOURCES.txt'
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
  running build_ext
  building 'cudamat.libcudamat' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\cudamat
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -O -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include
  nvcc fatal   : '-IC:\Users\Verfahrenstechnik\Anaconda3\include': expected a number
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cudamat
  Running setup.py clean for cudamat
Failed to build cudamat
Installing collected packages: cudamat
  Running setup.py install for cudamat ... error
    Complete output from command C:\Users\Verfahrenstechnik\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VERFAH~1\\AppData\\Local\\Temp\\pip-req-build-q_p29uw_\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\VERFAH~1\AppData\Local\Temp\pip-record-7yowy__3\install-record.txt --single-version-externally-managed --compile:
    C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-q_p29uw_\setup.py:23: UserWarning: MSVC (cl.exe) not found on PATH. Compilation may fail. Either set PATH to include the path to MSVC, or set NVCCFLAGS=--compiler-bindir=... to define it. Possibly also set NVCCFLAGS=--cl-version=2010 to override nvcc's MSVC version detection.
      warnings.warn("MSVC (cl.exe) not found on PATH. Compilation may "
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing top-level names to cudamat.egg-info\top_level.txt
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
    running build_ext
    building 'cudamat.libcudamat' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cudamat
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -O -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include
    nvcc fatal   : '-IC:\Users\Verfahrenstechnik\Anaconda3\include': expected a number
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\Users\Verfahrenstechnik\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VERFAH~1\\AppData\\Local\\Temp\\pip-req-build-q_p29uw_\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\VERFAH~1\AppData\Local\Temp\pip-record-7yowy__3\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-q_p29uw_\

So I install the NVIDIA GPU computing Toolkit v10.1

How to solve this problem?

**Comment by f0k** [comment]
> Then I also use the pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip.

Thank you, that's what I would have asked!

> ```
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -O -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include
> nvcc fatal : '-IC:\Users\Verfahrenstechnik\Anaconda3\include': expected a number
> ```

Hmm, this is interesting. The `-O` should have been followed by a number.
Investigating, this is something that was carried over from the original Makefile: https://github.com/cudamat/cudamat/blob/3803b3b4905403b9f00de742b98917389890cb00/Makefile
So it's still here: https://github.com/f0k/cudamat/commit/393e1ec637d2ea25372e7cb6131bb8121ab4e521#diff-2eeaed663bd0d25b7e608891384b7298R58

Can you download http://github.com/f0k/cudamat/archive/simplify-compile.zip, extract it, edit the file `setup.py` so it says `-O3` instead of `-O`, and then open the directory in a terminal and run `pip install .`? I will try to figure out if this is something that has only changed in a recent version of `nvcc`, or something that should never have worked anyway.

**Comment by f0k** [comment]
> I will try to figure out if this is something that has only changed in a recent version of `nvcc`, or something that should never have worked anyway.

It seems that gcc allows `-O` without any optimization level, but maybe not others, or `nvcc` checks itself. I've added `-O3` to the branch. Can you just try `pip install https://github.com/f0k/cudamat/archive/simplify-compile.zip` again? No need to download and adapt it.

**Comment by zerodrying** [comment]
It doesnot support on the latest version. 



PS>pip install https://github.com/f0k/cudamat/archive/simplify-compile.zip
Collecting https://github.com/f0k/cudamat/archive/simplify-compile.zip
  Downloading https://github.com/f0k/cudamat/archive/simplify-compile.zip
     / 532kB 1.6MB/s
Building wheels for collected packages: cudamat
  Building wheel for cudamat (setup.py) ... error
  Complete output from command C:\Users\Verfahrenstechnik\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VERFAH~1\\AppData\\Local\\Temp\\pip-req-build-0gnbmjs9\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\VERFAH~1\AppData\Local\Temp\pip-wheel-iqh36abg --python-tag cp36:
  C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-0gnbmjs9\setup.py:23: UserWarning: MSVC (cl.exe) not found on PATH. Compilation may fail. Either set PATH to include the path to MSVC, or set NVCCFLAGS=--compiler-bindir=... to define it. Possibly also set NVCCFLAGS=--cl-version=2010 to override nvcc's MSVC version detection.
    warnings.warn("MSVC (cl.exe) not found on PATH. Compilation may "
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
  running egg_info
  creating cudamat.egg-info
  writing cudamat.egg-info\PKG-INFO
  writing dependency_links to cudamat.egg-info\dependency_links.txt
  writing top-level names to cudamat.egg-info\top_level.txt
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  reading manifest file 'cudamat.egg-info\SOURCES.txt'
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
  running build_ext
  building 'cudamat.libcudamat' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\cudamat
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -O3 -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include
  nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cudamat
  Running setup.py clean for cudamat
Failed to build cudamat
Installing collected packages: cudamat
  Running setup.py install for cudamat ... error
    Complete output from command C:\Users\Verfahrenstechnik\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VERFAH~1\\AppData\\Local\\Temp\\pip-req-build-0gnbmjs9\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\VERFAH~1\AppData\Local\Temp\pip-record-i8jdhm47\install-record.txt --single-version-externally-managed --compile:
    C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-0gnbmjs9\setup.py:23: UserWarning: MSVC (cl.exe) not found on PATH. Compilation may fail. Either set PATH to include the path to MSVC, or set NVCCFLAGS=--compiler-bindir=... to define it. Possibly also set NVCCFLAGS=--cl-version=2010 to override nvcc's MSVC version detection.
      warnings.warn("MSVC (cl.exe) not found on PATH. Compilation may "
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing top-level names to cudamat.egg-info\top_level.txt
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
    running build_ext
    building 'cudamat.libcudamat' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cudamat
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -O3 -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj -IC:\Users\Verfahrenstechnik\Anaconda3\include -IC:\Users\Verfahrenstechnik\Anaconda3\include
    nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\Users\Verfahrenstechnik\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VERFAH~1\\AppData\\Local\\Temp\\pip-req-build-0gnbmjs9\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\VERFAH~1\AppData\Local\Temp\pip-record-i8jdhm47\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\VERFAH~1\AppData\Local\Temp\pip-req-build-0gnbmjs9\
(base) PS>

**Comment by f0k** [comment]
Did you see the UserWarning?
> ```
> UserWarning: MSVC (cl.exe) not found on PATH. Compilation may fail. Either set PATH to include the path to MSVC, or set NVCCFLAGS=--compiler-bindir=... to define it. Possibly also set NVCCFLAGS=--cl-version=2010 to override nvcc's MSVC version detection.
> ```
The shell you started this from does not have MSVC on its PATH. I think you will have to use the command prompt installed by MSVC, or follow the hints and update the PATH or NVCCFLAGS environment variable for this shell before running `pip install`. If you didn't install MSVC, then nvcc will not be able to compile anything at all. I've painfully figured out the steps for Windows 7 some time ago (https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne-on-Windows-7-(64-bit)#nvidia-gpu-support-cuda), this may help or not. Any guide for getting nvcc to run under Windows should work. Let me know if you can get it to work, and what was needed!

**Comment by anjaliagarwal8** [comment]
Hi
I got the same error and tried cuda-simplify-compile setup. My earlier error was resolved but I am getting this other error now. 

running install
F:/BCI/GenzelLab/mouseSleepAnalysis-master/cudamat-simplify-compile/cudamat-simplify-compile/setup.py:54: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
  shared_lib_extension = sysconfig.get_config_var('SO')
running bdist_egg
running egg_info
creating cudamat.egg-info
writing cudamat.egg-info\PKG-INFO
writing dependency_links to cudamat.egg-info\dependency_links.txt
writing top-level names to cudamat.egg-info\top_level.txt
writing manifest file 'cudamat.egg-info\SOURCES.txt'
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.7
creating build\lib.win-amd64-3.7\cudamat
copying cudamat\cudamat.py -> build\lib.win-amd64-3.7\cudamat
copying cudamat\learn.py -> build\lib.win-amd64-3.7\cudamat
copying cudamat\__init__.py -> build\lib.win-amd64-3.7\cudamat
copying cudamat\cudamat.cu -> build\lib.win-amd64-3.7\cudamat
copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.7\cudamat
copying cudamat\learn.cu -> build\lib.win-amd64-3.7\cudamat
copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.7\cudamat
copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.7\cudamat
running build_ext
building 'cudamat.libcudamat' extension
creating build\temp.win-amd64-3.7
creating build\temp.win-amd64-3.7\Release
creating build\temp.win-amd64-3.7\Release\cudamat
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc.exe -O3 -IC:\Users\Anjali\Anaconda3\include -IC:\Users\Anjali\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.7\Release\cudamat/cudamat.obj --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" -IC:\Users\Anjali\Anaconda3\include -IC:\Users\Anjali\Anaconda3\include
An exception has occurred, use %tb to see the full traceback.

SystemExit: error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\bin\\nvcc.exe' failed with exit status 1

Can you please help me resolve it?

**Comment by f0k** [comment]
> An exception has occurred, use %tb to see the full traceback.

Can you figure out how to get this traceback? That would probably help pinpoint the problem.

**Comment by anjaliagarwal8** [comment]
This is the traceback:

Traceback (most recent call last):

  File "<ipython-input-1-41f22a700b64>", line 1, in <module>
    runfile('F:/BCI/GenzelLab/mouseSleepAnalysis-master/cudamat-simplify-compile/cudamat-simplify-compile/setup.py', args='install', wdir='F:/BCI/GenzelLab/mouseSleepAnalysis-master/cudamat-simplify-compile/cudamat-simplify-compile')

  File "C:\Users\Anjali\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Anjali\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/BCI/GenzelLab/mouseSleepAnalysis-master/cudamat-simplify-compile/cudamat-simplify-compile/setup.py", line 100, in <module>
    url="https://github.com/cudamat/cudamat",

  File "C:\Users\Anjali\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)

  File "C:\Users\Anjali\Anaconda3\lib\distutils\core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))

SystemExit: error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\bin\\nvcc.exe' failed with exit status 1

Thank you @f0k

**Comment by anjaliagarwal8** [comment]
Hello @f0k ,
Can you please guide me in resolving this issue?

**Comment by anjaliagarwal8** [comment]
Finally I was able to run cudamat in my system going through all the fixes mentioned in the issues. I wrote all the errors I got and the fixes I tried here https://github.com/anjaliagarwal8/Sleep-Scoring/blob/main/Cudamat%20Installation.pdf

**Comment by Createuniverse** [comment]
hello! Respondent, nice to ask a question here!
I‘ve experienced the same question like the first one above
I've updated the PATH to cl.exe 
There're 4 pathes to cl.exe, and I added them all to th PATH
**__D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86**
**_D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x64_**
**D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86**
**D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64**
And the pathes are correct.
But it doesn't work.
It couldn't install like before.

**nvcc -O3 -ID:\Python3.9\include -ID:\Python3.9\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.9\Release\cudamat/cudamat.obj -ID:\Python3.9\include -ID:\Python3.9\include
      nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.5\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cudamat**

Then how could I solve it......

**Comment by Createuniverse** [comment]
hello! Respondent, nice to ask a question here!
I‘ve experienced the same question like the first one above
I've updated the PATH to cl.exe
There're 4 pathes to cl.exe, and I added them all to th PATH
__D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86
D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x64
D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86
D:\VisualStudio2019\VisualStudio2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64
And the pathes are correct.
But it doesn't work.
It couldn't install like before.

**nvcc -O3 -ID:\Python3.9\include -ID:\Python3.9\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.9\Release\cudamat/cudamat.obj -ID:\Python3.9\include -ID:\Python3.9\include
nvcc fatal : Cannot find compiler 'cl.exe' in PATH
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\nvcc.exe' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cudamat**

Then how could I solve it......

**Comment by anjaliagarwal8** [comment]
Could you check if the path you are adding does have cl.exe file inside? For me it was inside the bin folder.
