### ISSUE TITLE
Cannot import cudamat on OS X

### ISSUE THREAD

**Issue by davll** [cudamat/cudamat#33]
I installed cudamat on OS X (via pip).
The package is in /usr/local/lib/python2.7/site-packages/cudamat (since python is installed via homebrew)
However, it complains when I import cudamat.

It seems that `dlopen` is not able to find libcudamat.so

## Error Message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cudamat/__init__.py", line 1, in <module>
    from .cudamat import *
  File "cudamat/cudamat.py", line 13, in <module>
    os.path.dirname(__file__) or os.path.curdir, 'libcudamat.so'))
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(cudamat/libcudamat.so, 6): image not found
```

**Comment by f0k** [comment]
My divination skills further tell me that this solved your problem, so I'm closing this Issue.
