### ISSUE TITLE
Error on compiling on Windows with cmdclass

### ISSUE THREAD

**Issue by IronManMark20** [cudamat/cudamat#56]
Hello and thanks for your great efforts on adding Windows work. I just cloned and tried installing, but I got a problem with the line cmdclass={'build_ext': CUDA_build_ext}). I am guessing that it has something to do with being on Windows vs Linux, because the error pertains to drives, but anyway, here is the full traceback. If you help, I would appreciate it.

    running install
    running bdist_egg
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing top-level names to cudamat.egg-info\top_level.txt
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing pbr to cudamat.egg-info\pbr.json
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    installing library code to build\bdist.win32\egg
    running install_lib
    running build_py
    running build_ext
    building 'cudamat.libcudamat' extension
    Traceback (most recent call last):
      File "setup.py", line 121, in <module>
        cmdclass={'build_ext': CUDA_build_ext})
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\install.py", line 67, in run
      File "build\bdist.win32\egg\setuptools\command\install.py", line 109, in do_egg_install
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\bdist_egg.py", line 160, in run
      File "build\bdist.win32\egg\setuptools\command\bdist_egg.py", line 146, in call_command
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\install_lib.py", line 10, in run
      File "C:\Python27\lib\distutils\command\install_lib.py", line 111, in build
        self.run_command('build_ext')
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "build\bdist.win32\egg\setuptools\command\build_ext.py", line 50, in run
      File "C:\Python27\lib\distutils\command\build_ext.py", line 337, in run
        self.build_extensions()
      File "setup.py", line 41, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Python27\lib\site-packages\Pyrex\Distutils\build_ext.py", line 82, in build_extensions
        self.build_extension(ext)
      File "build\bdist.win32\egg\setuptools\command\build_ext.py", line 183, in build_extension
      File "C:\Python27\lib\distutils\command\build_ext.py", line 496, in build_extension
        depends=ext.depends)
      File "C:\Python27\lib\distutils\msvc9compiler.py", line 546, in compile
        extra_postargs)
      File "setup.py", line 70, in spawn
        os.path.dirname(find_executable("cl.exe", PATH))
      File "C:\Python27\lib\ntpath.py", line 215, in dirname
        return split(p)[0]
      File "C:\Python27\lib\ntpath.py", line 180, in split
        d, p = splitdrive(p)
      File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
        if len(p) > 1:
    TypeError: object of type 'NoneType' has no len()

**Comment by f0k** [comment]
The main problem seems to be this one:
```
  File "setup.py", line 70, in spawn
    os.path.dirname(find_executable("cl.exe", PATH))
```
We rely on "cl.exe" being on the PATH. If it isn't, `find_executable()` will return `None`, causing the error further below.

Are you sure you've got a recent enough version of MSVC installed? What happens if you run "cl.exe" on the command line, is it found? What happens if you run "nvcc --version"? What happens if you run "nvcc -c -O -o cudamat.obj cudamat/cudamat.cu"?

**Comment by IronManMark20** [comment]
Thanks, I didn't know cl was needed in the path. That solved it, kinda, except the only python versions I have are 2.7 and 3.5, and `nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported` :(

**Comment by f0k** [comment]
> That solved it, kinda, except the only python versions I have are 2.7 and 3.5, and `nvcc cannot find a supported version of Microsoft Visual Studio`

That's fully independent of the Python version, though. You'll just need to install a suitable MSVC version. Probably some version of "Microsoft Visual Studio Express" will do: https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx

**Comment by IronManMark20** [comment]
>That's fully independent of the Python version, though.

Won't having different MSVC versions mess up linking if it isn't the same as the version Python is compiled with? MSVC breaks compatibility I thought with every version, unlike GCC.

**Comment by f0k** [comment]
> Won't having different MSVC versions mess up linking if it isn't the same as the version Python is compiled with?

No, because we're not linking to anything from Python here, we just compile some `dll` file that will be loaded with `ctypes` (similar to how you can load Windows' DLLs with `ctypes` even though they are certainly compiled with a different compiler). We're actually abusing `build_ext` to build something that's not a Python extension, that's why it ended up being so complicated to do that with the `MSVCCompiler` class. #53 would be a better solution.

**Comment by IronManMark20** [comment]
Ah. Thanks! Good to know. I will try with 2010.

**Comment by IronManMark20** [comment]
Hm. No luck. I have VS 2010 installed, but I still get the problem. 

    running install
    running bdist_egg
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing top-level names to cudamat.egg-info\top_level.txt
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing pbr to cudamat.egg-info\pbr.json
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    installing library code to build\bdist.win32\egg
    running install_lib
    running build_py
    running build_ext
    building 'cudamat.libcudamat' extension
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN" -c -IC:\Python27\include -IC:\Python27\PC cudamat/cudamat.cu -o build\temp.win32-2.7\Release\cudamat/cudamat.obj -O --ptxas-options=-v --compiler-options=/nologo,/Ox,/MD,/W3,/GS-,/DNDEBUG
    nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\bin\\nvcc.exe' failed with exit status 1 


It clearly gives the dir of VS 2010 `"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN"`, what gives?

**Comment by f0k** [comment]
> It clearly gives the dir of VS 2010 `"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN"`, what gives?

I don't know. Maybe CUDA 7.5 doesn't actually support MSVC 2010? What happens if you directly run `nvcc -c -O -o cudamat.obj cudamat/cudamat.cu`? And if you pass `--compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe"`?
