### ISSUE TITLE
Another libcublas.so.7.5: cannot open shared object file problem

### ISSUE THREAD

**Issue by gammaguy** [cudamat/cudamat#58]
Great library.  Exactly what I'm looking for but....

I was able to install then run nosetests and bench_cudamat.py without errors (although I found if I run nosetests a number of times I get a "CUDAMatrix.sum exceeded threshold" or "cudamat.pow exceeded threshold" intermittently.  I put the full errors at the bottom in the Appendix). 

**I can run the example from the README.md in both the python shell or ipython but if I run it in Pycharm I get the following:**
______________________________________________
/home/paul/anaconda/bin/python /home/paul/PycharmProjects/untitled/po_cudamattest1967.py
Traceback (most recent call last):
  File "/home/paul/PycharmProjects/untitled/po_cudamattest1967.py", line 3, in <module>
    import cudamat as cm
  File "/home/paul/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/__init__.py", line 1, in <module>
    from .cudamat import *
  File "/home/paul/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/cudamat.py", line 18, in <module>
    _cudamat = load_library('libcudamat')
  File "/home/paul/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/cudamat.py", line 16, in load_library
    basename + ext))
  File "/home/paul/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/paul/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.7.5: cannot open shared object file: No such file or directory

Process finished with exit code 1
___________________________________________

I'm running Ubuntu 14.04, Cuda 7.5, Pycharm 5.0 on a i7-5950X, 32Gb with a Titan X.  My Theano programs run fine. I also tried it on Pycharm 4.5.

I compiled for a 5.2 Compute Capability via: 
NVCCFLAGS=-arch=sm_52 python setup.py install --user

Any thoughts would be welcome.  I still not great at Ubuntu so a little patience would be appreicated.

Regards
Paul

**Appendix:**
The two error I intermittently get between no error.

paul@speed:~/paul/cudamat/test$ nosetests
.........................................................
----------------------------------------------------------------------
Ran 57 tests in 0.790s

OK

paul@speed:~/paul/cudamat/test$ nosetests
................F........................................
======================================================================
FAIL: test_cudamat.test_sum_trans
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/paul/paul/cudamat/test/test_cudamat.py", line 367, in test_sum_trans
    assert np.max(np.abs(c2 - mt2.numpy_array)) < 10**-3, "Error in CUDAMatrix.sum exceeded threshold"
AssertionError: Error in CUDAMatrix.sum exceeded threshold

----------------------------------------------------------------------
Ran 57 tests in 0.831s

FAILED (failures=1)
paul@speed:~/paul/cudamat/test$ nosetests
..................................F......................
======================================================================
FAIL: test_cudamat.test_pow_matrix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/paul/paul/cudamat/test/test_cudamat.py", line 791, in test_pow_matrix
    assert np.max(np.abs(c - m1.numpy_array)) < 10**-2, "Error in cudamat.pow exceeded threshold"
AssertionError: Error in cudamat.pow exceeded threshold

----------------------------------------------------------------------
Ran 57 tests in 0.793s

FAILED (failures=1)

**Comment by f0k** [comment]
> I found if I run nosetests a number of times I get a "CUDAMatrix.sum exceeded threshold" or "cudamat.pow exceeded threshold" intermittently

That's reported in #54, the tolerances in the tests seem to be too strict for most GPUs. Feel free to help out with this.

> OSError: libcublas.so.7.5: cannot open shared object file: No such file or directory

I don't know Pycharm, but it seems you installed CUDA in a way Pycharm can't find it. Make sure the library location (e.g. /usr/local/cuda/lib64) is on `LD_LIBRARY_PATH` for Pycharm, or create a file `/etc/ld.so.conf.d/cuda` with a single line `/usr/local/cuda/lib64` and run `sudo ldconfig` to make CUDA available globally. If this solves the problem, please close the issue!

**Comment by gammaguy** [comment]
My machine's motherboard died but i'll have the replacement and be able to test it mid next week.  I'll get back to you then.  Thank you.
