### ISSUE TITLE
Error while calling test_cudamat.py

### ISSUE THREAD

**Issue by Rietaros** [cudamat/cudamat#65]
I have error while call test_cudamat.py. But when I call import cudamat in python, it's all fine.

Here is the detail:

python test_cudamat.py
Traceback (most recent call last):
  File "test_cudamat.py", line 4, in <module>
    import cudamat as cm
  File "/home/aries/Documents/deepnet-master/cudamat/cudamat.py", line 10, in <module>
    _cudamat = ct.cdll.LoadLibrary('libcudamat.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudamat.so: cannot open shared object file: No such file or directory

**Comment by f0k** [comment]
As documented (https://github.com/cudamat/cudamat/blob/master/INSTALL.md#testing), you must not call the test from the cudamat directory, otherwise it will try to import cudamat from there instead of the installed module.
