### ISSUE TITLE
test cudamat error

### ISSUE THREAD

**Issue by ElMouse** [cudamat/cudamat#78]
Hello!
I am running Windows 10
CUDA 5.5
Visual Studio 2008 Professional

have installed cudamat seemingly with no problems

now when i am running test cudamat i get:
```
C:\PRG\cudamat-master\test>python test_cudamat.py
Traceback (most recent call last):
  File "test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "C:\Python27\lib\site-packages\cudamat\__init__.py", line 1, in <module>
    from .cudamat import *
  File "C:\Python27\lib\site-packages\cudamat\cudamat.py", line 12, in <module>
    _cudamat = ct.cdll.LoadLibrary('libcudamat.dll')
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```
what might be the problem?

UPDATE: located libudamat.dll in C:\PRG\cudamat-master\cudamat  and added it to environmental variables. now i get:

```
C:\PRG\cudamat-master\test>python test_cudamat.py
Traceback (most recent call last):
  File "test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "C:\Python27\lib\site-packages\cudamat-0.3-py2.7.egg\cudamat\__init__.py", line 1, in <module>
    from .cudamat import *
  File "C:\Python27\lib\site-packages\cudamat-0.3-py2.7.egg\cudamat\cudamat.py", line 12, in <module>
    _cudamat = ct.cdll.LoadLibrary('libcudamat.dll')
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

I wonder if it has something to do with compiling cudamat with incorect platform? i dont know if platform is incorrect

```
C:\PRG\cudamat-master>python setup.py install

Microsoft (R) Program Maintenance Utility Version 9.00.21022.08
Copyright (C) Microsoft Corporation.  All rights reserved.

        nvcc -O --ptxas-options=-v -o libcudamat.dll --shared cudamat.cu cudamat_kernels.cu -lcublas
ptxas : info : 0 bytes gmem
ptxas : info : Compiling entry function '__cuda_dummy_entry__' for 'sm_10'
ptxas : info : Used 0 registers
cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(747): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

cudamat_kernels.cu(771): warning: division by zero

ptxas : info : 0 bytes gmem
ptxas : info : Compiling entry function '_Z10kApplyTanhPfS_j' for 'sm_10'
ptxas : info : Used 7 registers, 36 bytes smem, 16 bytes cmem[1]
ptxas : info : Compiling entry function '_Z16kMultByRowVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem
ptxas : info : Compiling entry function '_Z7kEqualsPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z5kSqrtPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z15kRandomGaussianPjPyPfj' for 'sm_10'
ptxas : info : Used 14 registers, 44 bytes smem, 12 bytes cmem[1]
ptxas : info : Compiling entry function '_Z13kAssignScalarPffj' for 'sm_10'
ptxas : info : Used 5 registers, 32 bytes smem
ptxas : info : Compiling entry function '_Z14kMaxColumnwisePfS_jj' for 'sm_10'
ptxas : info : Used 5 registers, 168 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z4kLogPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z9kSubtractPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z8kMaximumPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z13kAddColVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem
ptxas : info : Compiling entry function '_Z9kLessThanPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z16kSetSelectedRowsPfS_S_iii' for 'sm_10'
ptxas : info : Used 9 registers, 180 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z17kArgMaxColumnwisePfS_jj' for 'sm_10'
ptxas : info : Used 6 registers, 296 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z5kSignPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z11kAddColMultPfS_S_fjj' for 'sm_10'
ptxas : info : Used 11 registers, 52 bytes smem
ptxas : info : Compiling entry function '_Z12kGreaterThanPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z6kGammaPfS_j' for 'sm_10'
ptxas : info : Used 11 registers, 36 bytes smem, 72 bytes cmem[1]
ptxas : info : Compiling entry function '_Z11kSeedRandomPjPyj' for 'sm_10'
ptxas : info : Used 10 registers, 36 bytes smem, 12 bytes cmem[1]
ptxas : info : Compiling entry function '_Z5kMultPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z14kMinColumnwisePfS_jj' for 'sm_10'
ptxas : info : Used 5 registers, 168 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z9kApplyAbsPfS_j' for 'sm_10'
ptxas : info : Used 9 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z15kDivByRowVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z8kMinimumPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z10kPowMatrixPfS_S_j' for 'sm_10'
ptxas : info : Used 14 registers, 44 bytes smem, 88 bytes cmem[1]
ptxas : info : Compiling entry function '_Z12kSetRowSlicePfS_iiii' for 'sm_10'
ptxas : info : Used 8 registers, 48 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z10kAddScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z17kArgMinColumnwisePfS_jj' for 'sm_10'
ptxas : info : Used 6 registers, 296 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z19kApplySoftThresholdPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z15kDivByColVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z13kEqualsScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z4kPowPffS_j' for 'sm_10'
ptxas : info : Used 14 registers, 44 bytes smem, 88 bytes cmem[1]
ptxas : info : Compiling entry function '_Z12kGetRowSlicePfS_iiii' for 'sm_10'
ptxas : info : Used 8 registers, 48 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z13kDivideScalarPffS_j' for 'sm_10'
ptxas : info : Used 7 registers, 44 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z11kMaxRowwisePfS_jj' for 'sm_10'
ptxas : info : Used 6 registers, 168 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z4kExpPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z7kDividePfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z14kMaximumScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z13kAddRowVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem
ptxas : info : Compiling entry function '_Z15kLessThanScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z6kWherePfS_S_S_j' for 'sm_10'
ptxas : info : Used 6 registers, 52 bytes smem
ptxas : info : Compiling entry function '_Z14kArgMaxRowwisePfS_jj' for 'sm_10'
ptxas : info : Used 7 registers, 296 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z13kApplySigmoidPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z16kMultByColVectorPfS_S_jj' for 'sm_10'
ptxas : info : Used 11 registers, 48 bytes smem
ptxas : info : Compiling entry function '_Z18kGreaterThanScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z9kLogGammaPfS_j' for 'sm_10'
ptxas : info : Used 14 registers, 36 bytes smem, 240 bytes cmem[1]
ptxas : info : Compiling entry function '_Z14kRandomUniformPjPyPfj' for 'sm_10'
ptxas : info : Used 11 registers, 44 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z11kMultScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z11kMinRowwisePfS_jj' for 'sm_10'
ptxas : info : Used 6 registers, 168 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z17kApplyLog1PlusExpPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem, 4 bytes cmem[1]
ptxas : info : Compiling entry function '_Z4kAddPfS_S_j' for 'sm_10'
ptxas : info : Used 8 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z14kMinimumScalarPffS_j' for 'sm_10'
ptxas : info : Used 6 registers, 44 bytes smem
ptxas : info : Compiling entry function '_Z11kReciprocalPfS_j' for 'sm_10'
ptxas : info : Used 6 registers, 36 bytes smem
ptxas : info : Compiling entry function '_Z10kTransposePfS_ii' for 'sm_10'
ptxas : info : Used 8 registers, 1128 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z11kSelectRowsPfS_S_iii' for 'sm_10'
ptxas : info : Used 9 registers, 180 bytes smem, 8 bytes cmem[1]
ptxas : info : Compiling entry function '_Z14kArgMinRowwisePfS_jj' for 'sm_10'
ptxas : info : Used 7 registers, 296 bytes smem, 4 bytes cmem[1]
   Creating library libcudamat.lib and object libcudamat.exp
        nvcc -O --ptxas-options=-v -o libcudalearn.dll --shared learn.cu learn_kernels.cu -lcublas
ptxas : info : 0 bytes gmem
ptxas : info : Compiling entry function '__cuda_dummy_entry__' for 'sm_10'
ptxas : info : Used 0 registers
ptxas : info : 0 bytes gmem
ptxas : info : Compiling entry function '_Z22kMultiplyBySigmoidGradPfS_j' for 'sm_10'
ptxas : info : Used 7 registers, 36 bytes smem
   Creating library libcudalearn.lib and object libcudalearn.exp
running install
running bdist_egg
running egg_info
writing cudamat.egg-info\PKG-INFO
writing top-level names to cudamat.egg-info\top_level.txt
writing dependency_links to cudamat.egg-info\dependency_links.txt
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\cudamat
copying build\lib\cudamat\cudamat.py -> build\bdist.win32\egg\cudamat
copying build\lib\cudamat\learn.py -> build\bdist.win32\egg\cudamat
copying build\lib\cudamat\rnd_multipliers_32bit.txt -> build\bdist.win32\egg\cudamat
copying build\lib\cudamat\__init__.py -> build\bdist.win32\egg\cudamat
byte-compiling build\bdist.win32\egg\cudamat\cudamat.py to cudamat.pyc
byte-compiling build\bdist.win32\egg\cudamat\learn.py to learn.pyc
byte-compiling build\bdist.win32\egg\cudamat\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying cudamat.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying cudamat.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying cudamat.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying cudamat.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
cudamat.cudamat: module references __file__
cudamat.learn: module references __file__
creating 'dist\cudamat-0.3-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing cudamat-0.3-py2.7.egg
removing 'c:\python27\lib\site-packages\cudamat-0.3-py2.7.egg' (and everything under it)
creating c:\python27\lib\site-packages\cudamat-0.3-py2.7.egg
Extracting cudamat-0.3-py2.7.egg to c:\python27\lib\site-packages
cudamat 0.3 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\cudamat-0.3-py2.7.egg
Processing dependencies for cudamat==0.3
Finished processing dependencies for cudamat==0.3
```

**Comment by ElMouse** [comment]
Update:
Issue resolved.

Being an idiot i am - i had x86 python installed instead of the required x64

**Comment by f0k** [comment]
Good you figured it out! You could probably also use `NVCCFLAGS="--machine=32"` to compile for 32-bit, but I haven't tried.
