### ISSUE TITLE
undefined symbol: __gxx_personality_v0 error when running tests

### ISSUE THREAD

**Issue by romaad** [cudamat/cudamat#83]
```
python2 test_cudamat.py 
Traceback (most recent call last):
  File "test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "/home/eg7/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/__init__.py", line 2, in <module>
    from . import learn
  File "/home/eg7/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/learn.py", line 8, in <module>
    _cudalearn = load_library('libcudalearn')
  File "/home/eg7/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/cudamat.py", line 17, in load_library
    basename + ext))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/eg7/.local/lib/python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg/cudamat/libcudalearn.so: undefined symbol: __gxx_personality_v0

```

I have to note that python uses gcc 6.2.0 while cudamat was compiled using gcc-5

**Comment by JavaWarrior** [comment]
okay solving by recompiling with this:
http://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version

**Comment by f0k** [comment]
Closing because it's solved. Thank you for posting anyway! This may help others searching for the error message.
