### ISSUE TITLE
EE ===ERROR: Failure: OSError (/home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by poorniarumugam** [cudamat/cudamat#85]
EE ====================================================================== 
ERROR: Failure: OSError (/home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory)
Traceback (most recent call last):
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/facecnn/cudamat-master/test/test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 17, in load_library
    basename + ext))
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: OSError (/home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/facecnn/cudamat-master/test/test_learn.py", line 4, in <module>
    import cudamat as cm
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 17, in load_library
    basename + ext))
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 2 tests in 0.031s

FAILED (errors=2)

**Comment by f0k** [comment]
```
  File "/home/facecnn/cudamat-master/test/test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
```
There shouldn't be a `cudamat.py` in the same directory as `test_cudamat.py`. Did you put it there?
Just follow the guide at https://github.com/cudamat/cudamat/blob/master/INSTALL.md and it should work. If you encounter an error, tell exactly which steps you have taken and at what step the error occurs.

**Comment by poorniarumugam** [comment]
Thanks for your reply, but i am getting error while running the command nosetests. 
EE
======================================================================
ERROR: Failure: OSError (/home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/facecnn/cudamat-master/test/test_cudamat.py", line 3, in <module>
    import cudamat as cm
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 17, in load_library
    basename + ext))
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: OSError (/home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/facecnn/cudamat-master/test/test_learn.py", line 4, in <module>
    import cudamat as cm
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "/home/facecnn/cudamat-master/test/cudamat.py", line 17, in load_library
    basename + ext))
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/facecnn/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/facecnn/cudamat-master/test/libcudamat.so: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 2 tests in 0.120s

FAILED (errors=2)

**Comment by poorniarumugam** [comment]
..................F.......................................
======================================================================
FAIL: __main__.test_add_sums
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/facecnn/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_cudamat.py", line 424, in test_add_sums
    assert np.max(np.abs(c1 - mt1.numpy_array)) < 10**-3, "Error in CUDAMatrix.add_sums exceeded threshold"
AssertionError: Error in CUDAMatrix.add_sums exceeded threshold

----------------------------------------------------------------------
Ran 58 tests in 0.746s

FAILED (failures=1)

**Comment by f0k** [comment]
I think some tests are a little too strict. If you run it a couple of times, does it sometimes pass and sometimes fail?
