### ISSUE TITLE
Install Error on Windows

### ISSUE THREAD

**Issue by nwilliams98** [cudamat/cudamat#87]
Hi, 
I'm trying to learn cudamat and getting install error on Windows.  Any hints where to start with this?
I have an old version of Cuda running on my machine which works well with Jacket/Matlab but i'm trying to transition to Python. The error below is pretty unclear on install so hoping someone knows the next step.  Thanks!

c:\ProgramData\Anaconda3>python -m pip install c:\users\Nate\cudamat
Processing c:\users\nate\cudamat
Installing collected packages: cudamat
  Running setup.py install for cudamat ... error
    Complete output from command c:\ProgramData\Anaconda3\python.exe -u -c "impo
rt setuptools, tokenize;__file__='C:\\Users\\Nate\\AppData\\Local\\Temp\\pip-q62
0_npk-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read()
.replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install
--record C:\Users\Nate\AppData\Local\Temp\pip-nc21r8pg-record\install-record.txt
 --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
    running egg_info
    creating cudamat.egg-info
    writing cudamat.egg-info\PKG-INFO
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing top-level names to cudamat.egg-info\top_level.txt
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat

    running build_ext
    building 'cudamat.libcudamat' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cudamat
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nate\AppData\Local\Temp\pip-q620_npk-build\setup.py", line
121, in <module>
        cmdclass={'build_ext': CUDA_build_ext})
      File "c:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\ProgramData\Anaconda3\lib\distutils\dist.py", line 955, in run_co
mmands
        self.run_command(cmd)
      File "c:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.e
gg\setuptools\command\install.py", line 61, in run
      File "c:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545
, in run
        self.run_command('build')
      File "c:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135,
in run
        self.run_command(cmd_name)
      File "c:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
        self.distribution.run_command(command)
      File "c:\ProgramData\Anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
        cmd_obj.run()
      File "c:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.e
gg\setuptools\command\build_ext.py", line 77, in run
      File "c:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_buil
d_ext.py", line 185, in run
        _build_ext.build_ext.run(self)
      File "c:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 3
39, in run
        self.build_extensions()
      File "C:\Users\Nate\AppData\Local\Temp\pip-q620_npk-build\setup.py", line
41, in build_extensions
        build_ext.build_extensions(self)
      File "c:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_buil
d_ext.py", line 193, in build_extensions
        self.build_extension(ext)
      File "c:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.e
gg\setuptools\command\build_ext.py", line 198, in build_extension
      File "c:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 5
33, in build_extension
        depends=ext.depends)
      File "c:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 382,
in compile
        self.spawn(args)
      File "C:\Users\Nate\AppData\Local\Temp\pip-q620_npk-build\setup.py", line
70, in spawn
        os.path.dirname(find_executable("cl.exe", PATH))
      File "c:\ProgramData\Anaconda3\lib\ntpath.py", line 242, in dirname
        return split(p)[0]
      File "c:\ProgramData\Anaconda3\lib\ntpath.py", line 204, in split
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

    ----------------------------------------
Command "c:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\Nate\\AppData\\Local\\Temp\\pip-q620_npk-build\\setup.py';f
=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f
.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Nate\A
ppData\Local\Temp\pip-nc21r8pg-record\install-record.txt --single-version-extern
ally-managed --compile" failed with error code 1 in C:\Users\Nate\AppData\Local\
Temp\pip-q620_npk-build\

**Comment by f0k** [comment]
Ah, seems `setup.py` assumes there's always a `PATH` environment variable set, but you haven't. Looking further, even `distutils.spawn.find_executable` assumes there's always a `PATH` environment variable set. This has been reported as a bug before, but wasn't fixed because third-party code monkey-patches various parts of `distutils` and could be broken by any change to it: https://bugs.python.org/issue12420

Can you try `pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip` and let me know what happens? I just updated it so it can cope with an undefined `PATH` (it's PR #79). This should be less brittle, it only requires you to have `nvcc` set up correctly. Note that this might require you to set the `PATH` environment variable eventually to include the path to `nvcc`.

**Comment by SerialDev** [comment]
I could reproduce this on my machine
```
Collecting http://github.com/f0k/cudamat/archive/simplify-compile.zip
  Downloading http://github.com/f0k/cudamat/archive/simplify-compile.zip (92kB)
    100% |████████████████████████████████| 102kB 282kB/s
Building wheels for collected packages: cudamat
  Running setup.py bdist_wheel for cudamat ... error
  Complete output from command C:\Users\Carlos\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Carlos\\AppData\\Local\\Temp\\pip-e5o8rkm7-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Carlos\AppData\Local\Temp\tmpbudse8ompip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
  running egg_info
  creating cudamat.egg-info
  writing cudamat.egg-info\PKG-INFO
  writing dependency_links to cudamat.egg-info\dependency_links.txt
  writing top-level names to cudamat.egg-info\top_level.txt
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  reading manifest file 'cudamat.egg-info\SOURCES.txt'
  writing manifest file 'cudamat.egg-info\SOURCES.txt'
  copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
  copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
  running build_ext
  building 'cudamat.libcudamat' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\cudamat
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe -O -IC:\Users\Carlos\Anaconda3\include -IC:\Users\Carlos\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64" -IC:\Users\Carlos\Anaconda3\include -IC:\Users\Carlos\Anaconda3\include
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/../../../VC/INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
  nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
  cudamat.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin\\nvcc.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for cudamat
  Running setup.py clean for cudamat
Failed to build cudamat
Installing collected packages: cudamat
  Running setup.py install for cudamat ... error
    Complete output from command C:\Users\Carlos\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Carlos\\AppData\\Local\\Temp\\pip-e5o8rkm7-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Carlos\AppData\Local\Temp\pip-fbykqlgr-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.py -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\__init__.py -> build\lib.win-amd64-3.6\cudamat
    running egg_info
    writing cudamat.egg-info\PKG-INFO
    writing dependency_links to cudamat.egg-info\dependency_links.txt
    writing top-level names to cudamat.egg-info\top_level.txt
    reading manifest file 'cudamat.egg-info\SOURCES.txt'
    writing manifest file 'cudamat.egg-info\SOURCES.txt'
    copying cudamat\cudamat.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\cudamat_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\learn_kernels.cu -> build\lib.win-amd64-3.6\cudamat
    copying cudamat\rnd_multipliers_32bit.txt -> build\lib.win-amd64-3.6\cudamat
    running build_ext
    building 'cudamat.libcudamat' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cudamat
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe -O -IC:\Users\Carlos\Anaconda3\include -IC:\Users\Carlos\Anaconda3\include -c cudamat/cudamat.cu -o build\temp.win-amd64-3.6\Release\cudamat/cudamat.obj --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64" -IC:\Users\Carlos\Anaconda3\include -IC:\Users\Carlos\Anaconda3\include
    C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/../../../VC/INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    cudamat.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin\\nvcc.exe' failed with exit status 2

```

**Comment by f0k** [comment]
Thank you for your report.

> I could reproduce this on my machine
> ```
> fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
> ```

I would assume this is not a fault of cudamat, please check the [search results of a major search engine](https://www.google.at/search?q=Cannot+open+include+file%3A+'corecrt.h') and report back whether you found a solution (and what the solution was)!
