### ISSUE TITLE
cudamat cannot initialize

### ISSUE THREAD

**Issue by asgharrazavi** [cudamat/cudamat#88]
>>> import cudamat as cm
>>> cm.cublas_init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cudamat.py", line 1561, in cublas_init
    raise CUDAMatException('error initializing CUBLAS: (err=%u)' % err)
 
cudamat.CUDAMatException: error initializing CUBLAS: (err=-2)

Any ideas?

**Comment by asgharrazavi** [comment]
> As for your particular problem, you could hack your cudamat installation to return the actual status code instead of -2

Could you please explain how to do this?

**Comment by f0k** [comment]
1. `git clone` the repository to your computer, if you haven't done so.
2. Edit the file I mentioned so the function `cublas_init` looks like this:
```c
EXPORT int cublas_init() {
    return cublasInit();
}
```
3. Run the installation command appropriate for your needs (https://github.com/cudamat/cudamat/blob/master/INSTALL.md#installation).

**Comment by asgharrazavi** [comment]
I did your above steps but still get the same error.

I was having difficult time installing cudamat, so, instead I only built it by "python setup.py build" and then change directory to the build folder and ran python and import cudamat. 

If I try to install it by "python setup.py install" , I get the following error:

```
$python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cudamat as cm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cudamat/__init__.py", line 1, in <module>
    from .cudamat import *
  File "cudamat/cudamat.py", line 19, in <module>
    _cudamat = load_library('libcudamat')
  File "cudamat/cudamat.py", line 17, in load_library
    basename + ext))
  File "/home/asr2013/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/asr2013/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: cudamat/libcudamat.so: cannot open shared object file: No such file or directory
```

**Comment by f0k** [comment]
> I did your above steps but still get the same error.

If it still returns `err=-2`, you're not running your customized version.

> If I try to install it by "python setup.py install" , I get the following error:

No, you get the error when you try to import cudamat, not when you try to install it. The reason, if I see correctly, is that you ran python from the cudamat directory. When you run `import cudamat`, Python will then see that there's a `cudamat` directory, and try to import from there instead of the version you installed. You need to `cd` somewhere else.

**Comment by katosh** [comment]
I had the same error `(err=-2)` on `import cudamat` or the `nosetests`, and the modification suggested by @f0k changed it to `(err=1)`.  Does that correspond to `CUBLAS_STATUS_NOT_INITIALIZED`?

**Comment by katosh** [comment]
My problem was resolved with a driver update.

**Comment by f0k** [comment]
> Does that correspond to CUBLAS_STATUS_NOT_INITIALIZED?

Yes, according to `cublas_api.h` (in `/usr/local/cuda/include/cublas_api.h` on a standard linux installation of CUDA):
```
/* CUBLAS status type returns */
typedef enum{
    CUBLAS_STATUS_SUCCESS         =0,
    CUBLAS_STATUS_NOT_INITIALIZED =1,
    CUBLAS_STATUS_ALLOC_FAILED    =3,
    CUBLAS_STATUS_INVALID_VALUE   =7,
    CUBLAS_STATUS_ARCH_MISMATCH   =8,
    CUBLAS_STATUS_MAPPING_ERROR   =11,
    CUBLAS_STATUS_EXECUTION_FAILED=13,
    CUBLAS_STATUS_INTERNAL_ERROR  =14,
    CUBLAS_STATUS_NOT_SUPPORTED   =15,
    CUBLAS_STATUS_LICENSE_ERROR   =16
} cublasStatus_t;
```

> My problem was resolved with a driver update.

Nice. I'd still welcome a PR that improves error handling as outlined in https://github.com/cudamat/cudamat/pull/29#discussion_r16045891, if you feel like it!

**Comment by anjaliagarwal8** [comment]
@katosh Hey I am also getting the same error (err=1). Which driver update solved the issue?
Also which CUDA version did you use?

**Comment by katosh** [comment]
@anjaliagarwal8 I am sorry, this was more than 2 years ago and I cannot exactly reconstruct. I can only guess that we updated to the lates driver version and CUDA of that time.

**Comment by anjaliagarwal8** [comment]
Ah, I see maybe then I will try with older versions of CUDA. Thanks a lot!!
