### ISSUE TITLE
I have an error in importing cudamat.

### ISSUE THREAD

**Issue by bigsum71** [cudamat/cudamat#90]
Hi,
I set up cudamat in Windows environment.
At first, I tried to install cudamat in source directory, but I failed.
And so, I retried it as you guided (pip install http://gitbut....zip), and I succeeded installing it.
I confirmed the cudamat directory was created in Anaconda's site-packages directory.
And then, I tested whether it works well. (python -> import cudamat)
But, it won't work well. I had following error messages.
Please, let me know how to solve this problem. Thank you.

=========================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\cudamat\__init__.py", line 1, in <module>
    from .cudamat import *
  File "C:\Anaconda3\lib\site-packages\cudamat\cudamat.py", line 15, in <module>
    _cudamat = load_library('libcudamat')
  File "C:\Anaconda3\lib\site-packages\cudamat\cudamat.py", line 13, in load_library
    basename + sysconfig.get_config_var('SO')))
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126]

**Comment by f0k** [comment]
Googling for `WinError 126` tells that it's `The specified module could not be found`. This either means the `libcudamat` DLL is missing, or it depends on other DLLs that are missing. It might be the same problem as in https://github.com/cudamat/cudamat/issues/81#issuecomment-313652149, where the files were given a different name during compilation than expected during import. I'm neither a Windows nor Anaconda user, so it's difficult for me to understand what's happening.

Can you do `dir C:\Anaconda3\lib\site-packages\cudamat`, and `python -c "import sysconfig; print sysconfig.get_config_var('SO')"`?

**Comment by atormanen** [comment]
C:\Program Files\Python35\Lib\site-packages\cudamat>python -c "import sysconfig; print (sysconfig.get_config_var('SO'))"
.pyd

C:\Program Files\Python35\Lib\site-packages\cudamat>dir
 Volume in drive C is OS
 Volume Serial Number is 9D68-3FF4

 Directory of C:\Program Files\Python35\Lib\site-packages\cudamat

12/23/2017  02:41 PM    <DIR>          .
12/23/2017  02:41 PM    <DIR>          ..
12/23/2017  02:41 PM            47,232 cudamat.cu
12/23/2017  02:41 PM            47,348 cudamat.py
12/23/2017  02:41 PM            26,861 cudamat_kernels.cu
12/23/2017  02:41 PM               831 learn.cu
12/23/2017  02:41 PM               504 learn.py
12/23/2017  02:41 PM               374 learn_kernels.cu
12/23/2017  02:41 PM               898 libcudalearn.cp35-win_amd64.exp
12/23/2017  02:41 PM             2,304 libcudalearn.cp35-win_amd64.lib
12/23/2017  02:41 PM           256,512 libcudalearn.cp35-win_amd64.pyd
12/23/2017  02:41 PM             9,620 libcudamat.cp35-win_amd64.exp
12/23/2017  02:41 PM            18,070 libcudamat.cp35-win_amd64.lib
12/23/2017  02:41 PM           503,296 libcudamat.cp35-win_amd64.pyd
12/23/2017  02:41 PM           176,308 rnd_multipliers_32bit.txt
12/23/2017  02:41 PM                43 __init__.py
12/23/2017  02:41 PM    <DIR>          __pycache__
              14 File(s)      1,090,201 bytes
               3 Dir(s)  19,413,135,360 bytes free

C:\Program Files\Python35\Lib\site-packages\cudamat>

**Comment by f0k** [comment]
Hmm, that's the same problem as in https://github.com/cudamat/cudamat/issues/81#issuecomment-313652149. My guess would be that you accidentally used a different Python version for compilation.
What command did you run for installing cudamat?
What happens if you use: `pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip`? That one uses a slightly different approach for compilation.

**Comment by HanwenCao** [comment]
Hi. I have the same error in Windoze. I tried pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip 
Then cudamat was installed. But it still cannot be imported.
I was wondering which files I should rename? Or how could I fix it otherwise?

Thanks!
