### ISSUE TITLE
install error on windows 10

### ISSUE THREAD

**Issue by CoolPhilChen** [cudamat/cudamat#92]
# TypeError: object of type 'NoneType' has no len()
Hi, I'm trying to install cudamat on my computer, but I have some problems. Can anyone offer me some help? Thanks a lot!

## desktop information:
os: windows10
GPU: Nvidia Quadro K1200
CUDA: 8.0.61_win10

After I run in command `python setup.py install`, I got the following
## Error information:
running install
running bdist_egg
running egg_info
writing dependency_links to cudamat.egg-info\dependency_links.txt
writing top-level names to cudamat.egg-info\top_level.txt
writing cudamat.egg-info\PKG-INFO
reading manifest file 'cudamat.egg-info\SOURCES.txt'
writing manifest file 'cudamat.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'cudamat.libcudamat' extension
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    cmdclass={'build_ext': CUDA_build_ext})
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 41, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Anaconda3\envs\tf-gpu\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\Anaconda3\envs\tf-gpu\lib\distutils\_msvccompiler.py", line 382, in compile
    self.spawn(args)
  File "setup.py", line 70, in spawn
    os.path.dirname(find_executable("cl.exe", PATH))
  File "D:\Anaconda3\envs\tf-gpu\lib\ntpath.py", line 239, in dirname
    return split(p)[0]
  File "D:\Anaconda3\envs\tf-gpu\lib\ntpath.py", line 204, in split
    d, p = splitdrive(p)
  File "D:\Anaconda3\envs\tf-gpu\lib\ntpath.py", line 139, in splitdrive
    if len(p) >= 2:
TypeError: object of type 'NoneType' has no len()

**Comment by f0k** [comment]
Please try `pip install http://github.com/f0k/cudamat/archive/simplify-compile.zip` from #79 and report back! I haven't merged this yet primarily because I'm not sure if it breaks anything for Mac.

**Comment by lvliming** [comment]
I want to ask that have you solved this problem? I am facing the same problem with you~

**Comment by CoolPhilChen** [comment]
@lvliming Sorry, I didn't.
