### ISSUE TITLE
cudamat.cudamat.CUDAMatException: error initializing CUBLAS: (err=1)

### ISSUE THREAD

**Issue by SueSu-Wish** [cudamat/cudamat#96]
>>> import cudamat as cm
>>> cm.cublas_init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/suesu/.local/lib/python2.7/site-packages/cudamat/cudamat.py", line 1561, in cublas_init
    raise CUDAMatException('error initializing CUBLAS: (err=%u)' % err)
cudamat.cudamat.CUDAMatException: error initializing CUBLAS: (err=1)

**Comment by f0k** [comment]
Please follow https://github.com/cudamat/cudamat/issues/94#issuecomment-365944588 to check if CUDA is installed correctly.
If the error persists, please follow https://github.com/cudamat/cudamat/issues/88#issuecomment-311393379 to have cudamat return an error code that you can look up in http://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t.
A pull request to improve error handling in cudamat would be welcome, see https://github.com/cudamat/cudamat/pull/29#discussion_r16045891.
Please let us know if (and how) you solved the error to help others searching for a solution. Cheers!

**Comment by zhaoji-1024** [comment]
cm.cuda_set_device(0)

**Comment by zhaoji-1024** [comment]
cm.cublas_init()
cm.cuda_set_device(0)

**Comment by anjaliagarwal8** [comment]
Was the issue resolved? I am also getting an error initializing CUBLAS: (err=1)
