### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by beew** [cudamat/cudamat#97]
I installed with
```
 NVCCFLAGS=-arch=sm_61 python3 setup.py install --user
```
It installed without problem, but running test results in these errors
```
nosetests
..................F......................................E.
======================================================================
ERROR: test_cudamat.test_correlate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/bernard/Downloads/cudamat/test/test_cudamat.py", line 1204, in test_correlate
    for h in range(-(km/2), km/2 + 1):
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
FAIL: test_cudamat.test_add_sums
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/bernard/Downloads/cudamat/test/test_cudamat.py", line 424, in test_add_sums
    assert np.max(np.abs(c1 - mt1.numpy_array)) < 10**-3, "Error in CUDAMatrix.add_sums exceeded threshold"
AssertionError: Error in CUDAMatrix.add_sums exceeded threshold

----------------------------------------------------------------------
Ran 59 tests in 1.008s

FAILED (errors=1, failures=1)
```
OS is Ubuntu 16.04.4, python3.5, GPU Nvidia GTX1070 CUDA9.1

**Comment by beew** [comment]
With python2 there was no type error

```
$ nosetests
..................F........................................
======================================================================
FAIL: test_cudamat.test_add_sums
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bernard/Downloads/cudamat_py2/test/test_cudamat.py", line 424, in test_add_sums
    assert np.max(np.abs(c1 - mt1.numpy_array)) < 10**-3, "Error in CUDAMatrix.add_sums exceeded threshold"
AssertionError: Error in CUDAMatrix.add_sums exceeded threshold

----------------------------------------------------------------------
Ran 59 tests in 0.985s

FAILED (failures=1)
```

**Comment by f0k** [comment]
> With python2 there was no type error

Oh, good catch... that was introduced in #73, which wasn't tested in Python 3 (a CI system would have caught this, but we'd need a CI system with CUDA support). A PR using `//2` instead of `/2` would be welcome.
The second one is due to some of the tolerances being too strict: #54. A PR for this would be welcome.

**Comment by beew** [comment]
I just install again in python3.7.6, still same test error.

**Comment by f0k** [comment]
> I just install again in python3.7.6, still same test error.

Yes, the invitation for PRs as per my previous comment is still open! Would you like to send two pull requests? Would you need help with the process?

**Comment by beew** [comment]
I  already has the latest by git clone the source. How to send two pull requests?
